# Занятие 11

In [58]:
import numpy as np

In [59]:
scalar_value = 10

simple_vector = np.array([1, 5, 2, 3])

simple_matrix = np.array([
    [4, 3, 2, 1],
    [7, 5, 8, 2]
])

In [60]:
simple_vector.shape

(4,)

In [61]:
simple_matrix.shape

(2, 4)

In [62]:
scalar_value + scalar_value

20

In [63]:
print(f'{scalar_value} + {simple_vector} = {[f"{scalar_value} + {v}" for v in simple_vector]}')
print(scalar_value + simple_vector)

10 + [1 5 2 3] = ['10 + 1', '10 + 5', '10 + 2', '10 + 3']
[11 15 12 13]


In [64]:
print(f"{scalar_value}\n")
print(f"{simple_matrix}\n")
print(scalar_value + simple_matrix)

10

[[4 3 2 1]
 [7 5 8 2]]

[[14 13 12 11]
 [17 15 18 12]]


In [65]:
print(f"{simple_vector}\n")
print(f"{simple_matrix}\n")
print(simple_vector + simple_matrix)

[1 5 2 3]

[[4 3 2 1]
 [7 5 8 2]]

[[ 5  8  4  4]
 [ 8 10 10  5]]


In [66]:
print(f"{simple_matrix}\n")
print(simple_matrix + simple_matrix)

[[4 3 2 1]
 [7 5 8 2]]

[[ 8  6  4  2]
 [14 10 16  4]]


In [67]:
print(f'{scalar_value} * {simple_vector} = {[f"{scalar_value} * {v}" for v in simple_vector]}')
print(np.dot(simple_vector, scalar_value))

10 * [1 5 2 3] = ['10 * 1', '10 * 5', '10 * 2', '10 * 3']
[10 50 20 30]


In [68]:
print(np.dot(scalar_value, simple_matrix))

[[40 30 20 10]
 [70 50 80 20]]


In [69]:
print(simple_vector)
print("1 * 1 + 5 * 5 + 2 * 2 + 3 * 3 = 1 + 25 + 4 + 9 = 39")
print(np.dot(simple_vector, simple_vector))

[1 5 2 3]
1 * 1 + 5 * 5 + 2 * 2 + 3 * 3 = 1 + 25 + 4 + 9 = 39
39


In [70]:
#print(np.dot(simple_vector, simple_matrix))

In [71]:
simple_vector = np.expand_dims(simple_vector, -1)
simple_vector.shape

(4, 1)

In [72]:
result = np.dot(simple_matrix, simple_vector)
print(f"{simple_matrix.shape} * {simple_vector.shape} = {result.shape}")
print(result)

(2, 4) * (4, 1) = (2, 1)
[[26]
 [54]]


In [73]:
print(f"shape = {simple_matrix.shape}\n{simple_matrix}\n")
print(f"shape = {simple_matrix.T.shape}\n{simple_matrix.T}")

shape = (2, 4)
[[4 3 2 1]
 [7 5 8 2]]

shape = (4, 2)
[[4 7]
 [3 5]
 [2 8]
 [1 2]]


In [74]:
result = np.dot(simple_vector.T, simple_matrix.T)
print(f"{simple_vector.T.shape} * {simple_matrix.T.shape} = {result.shape}")
print(result)

(1, 4) * (4, 2) = (1, 2)
[[26 54]]


In [75]:
#result = np.dot(simple_matrix, simple_matrix)

In [76]:
result = np.dot(simple_matrix, simple_matrix.T)
print(f"{simple_matrix}\n\n{simple_matrix.T}\n\n{simple_matrix.shape} * {simple_matrix.T.shape} = {result.shape}")
print(result)

[[4 3 2 1]
 [7 5 8 2]]

[[4 7]
 [3 5]
 [2 8]
 [1 2]]

(2, 4) * (4, 2) = (2, 2)
[[ 30  61]
 [ 61 142]]


4 * 4 + 3 * 3 + 2 * 2 + 1 * 1 = 16 + 9 + 4 + 1 = 30
4 * 7 + 3 * 5 + 2 * 8 + 1 * 2 = 28 + 15 + 16 + 2 = 61

7 * 4 + 5 * 3 + 8 * 2 + 2 * 1 = 28 + 15 + 16 + 2 = 61
7 * 7 + 5 * 5 + 8 * 8 + 2 * 2 = 49 + 25 + 64 + 4 = 142

In [77]:
def matsum_vector_scalar(vector, scalar):
    return [v + scalar for v in vector]

In [78]:
print(f"{matsum_vector_scalar(simple_vector, scalar_value)} = {simple_vector + scalar_value}")

[array([11]), array([15]), array([12]), array([13])] = [[11]
 [15]
 [12]
 [13]]


In [79]:
def matsum_matrix_scalar(matrix, scalar):
    return [[v + scalar for v in row] for row in matrix]

In [80]:
print(f"simple python: {matsum_matrix_scalar(simple_matrix, scalar_value)}\nnumpy: {(simple_matrix + scalar_value).tolist()}")

simple python: [[np.int64(14), np.int64(13), np.int64(12), np.int64(11)], [np.int64(17), np.int64(15), np.int64(18), np.int64(12)]]
numpy: [[14, 13, 12, 11], [17, 15, 18, 12]]


In [81]:
def matmul_vector_vector(vector_first, vector_second):
    result = 0
    for v_f, v_s in zip(vector_first, vector_second):
        result += v_f * v_s
    return result

In [82]:
#print(f"{matmul_vector_vector(simple_vector, simple_vector)} = {np.dot(simple_vector, simple_vector)}")

In [83]:
def matmul_vector_matrix(matrix, vector):
    result = []
    for row in matrix:
        tmp = 0
        for m_v, v in zip(row, vector):
            tmp += m_v * v
        result.append(tmp)
    return result

In [84]:
print(f"{matmul_vector_matrix(simple_matrix, simple_vector)} = {np.dot(simple_matrix, simple_vector)}")

[array([26]), array([54])] = [[26]
 [54]]


**Лекарство от скуки _(домашка)_**

Реализовать оставшиеся методы (сложение матриц, перемножение матриц, транспонирование)

In [85]:
def matrix_add(A, B):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] + B[i][j])
        result.append(row)
    return np.array(result)

def matrix_sub(A, B):  
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(A[0])):
            row.append(A[i][j] - B[i][j])
        result.append(row)
    return np.array(result)

def matrix_mul(A, B):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(B[0])):
            total = 0
            for k in range(len(A[0])):
                total += A[i][k] * B[k][j]
            row.append(total)
        result.append(row)
    return np.array(result)

def matrix_transpose(A):
    result = []
    for j in range(len(A[0])):
        row = []
        for i in range(len(A)):
            row.append(A[i][j])
        result.append(row)
    return np.array(result)

In [86]:
# Вариант 1
A = np.array([[1,2,4],[7,5,-2],[-2,1,3]])
B = np.array([[-1,0,3],[2,-6,1],[-7,1,5]])
C = np.array([[-2,3],[4,0],[7,-1]])

print("A+B:\n", matrix_add(A,B))
print("\nB-A:\n", matrix_sub(B,A))
print("\nA*C:\n", matrix_mul(A,C))
print("\nA*B*C:\n", matrix_mul(matrix_mul(A,B),C))

A+B:
 [[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]

B-A:
 [[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]

A*C:
 [[34 -1]
 [-8 23]
 [29 -9]]

A*B*C:
 [[ 193 -100]
 [ -50   35]
 [  92  -61]]


In [87]:
# Вариант 2
A = np.array([[0,3,4],[-7,1,-2],[2,-1,3]])
B = np.array([[1,2,4],[7,0,-2],[-3,-2,5]])
C = np.array([[-3,2],[0,4],[-1,7]])

print("A+B:\n", matrix_add(A,B))
print("\nB-A:\n", matrix_sub(B,A))
print("\nA*C:\n", matrix_mul(A,C))
print("\nA*B*C:\n", matrix_mul(matrix_mul(A,B),C))

A+B:
 [[ 1  5  8]
 [ 0  1 -4]
 [-1 -3  8]]

B-A:
 [[ 1 -1  0]
 [14 -1  0]
 [-5 -1  2]]

A*C:
 [[ -4  40]
 [ 23 -24]
 [ -9  21]]

A*B*C:
 [[ -41   84]
 [  22 -308]
 [  17  139]]


In [88]:
# Вариант 3
A = np.array([[5,2,9],[7,0,-2],[-2,1,6]])
B = np.array([[1,-2,1],[7,5,-2],[-2,8,3]])
C = np.array([[-2,3],[4,5],[0,-1]])

print("A+B:\n", matrix_add(A,B))
print("\nB-A:\n", matrix_sub(B,A))
print("\nA*C:\n", matrix_mul(A,C))
print("\nA*B*C:\n", matrix_mul(matrix_mul(A,B),C))

A+B:
 [[ 6  0 10]
 [14  5 -4]
 [-4  9  9]]

B-A:
 [[-4 -4 -8]
 [ 0  5  0]
 [ 0  7 -3]]

A*C:
 [[ -2  16]
 [-14  23]
 [  8  -7]]

A*B*C:
 [[ 286  335]
 [-142 -118]
 [ 242  250]]


In [89]:
# Вариант 4
A = np.array([[1,-2,8],[7,5,-2],[-2,3,0]])
B = np.array([[0,2,4],[1,-3,-2],[-2,1,3]])
C = np.array([[0,3],[5,-4],[7,-1]])

print("A+B:\n", matrix_add(A,B))
print("\nB-A:\n", matrix_sub(B,A))
print("\nA*C:\n", matrix_mul(A,C))
print("\nA*B*C:\n", matrix_mul(matrix_mul(A,B),C))

A+B:
 [[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]

B-A:
 [[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]

A*C:
 [[ 46   3]
 [ 11   3]
 [ 15 -18]]

A*B*C:
 [[ 304 -150]
 [  69   27]
 [-163   75]]


In [90]:
# Вариант 5
A = np.array([[9,2,4],[7,5,-5],[6,-2,3]])
B = np.array([[8,2,4],[0,1,-3],[-2,1,6]])
C = np.array([[-2,0],[4,8],[1,-1]])

print("A+B:\n", matrix_add(A,B))
print("\nB-A:\n", matrix_sub(B,A))
print("\nA*C:\n", matrix_mul(A,C))
print("\nA*B*C:\n", matrix_mul(matrix_mul(A,B),C))

A+B:
 [[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]

B-A:
 [[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]

A*C:
 [[ -6  12]
 [  1  45]
 [-17 -19]]

A*B*C:
 [[ 22 138]
 [-93 129]
 [ 16  56]]


In [ ]:
det1 = np.linalg.det(np.array([
    [4, 0, 4, 5],
    [0, 1, 5, 6],
    [-2, 2, 2, 0],
    [1, -5, 1, 3]
]))

det7 = np.linalg.det(np.array([
    [3, 2, 0, 1],
    [0, 2, 2, 3],
    [1, 5, 6, 1],
    [-2, 0, 3, 2]
]))

print(f"Определитель 1: {det1}")
print(f"Определитель 7: {det7}")

Определитель 1: 187.99999999999983
Определитель 7: 64.99999999999999
